pub const SPLASHES: &[&str] = &[
    "brain loss",
    "i resized my Gentoo root and now it won’t boot",
    "this shcks i quir",
    "i guess we'll never know",
    "soon someone is going to document installing Gentoo on a computer made of lemons and potatoes",
    "at least with Path of Pain you don't have the chance to delete glibc",
    "VC minix install?",
    "He could’ve chosen French, Instead he chose failure",
    "thread 'main' panicked at src/main.rs:5:5",
    "Update README.md",
    "I'm not sure what I'm doing",
    "REWRITE IT IN RUST!!",
    "It's like a freight train",
    "With the lights out, it's less dangerous",
    "if you see this, consider yourself lucky!",
    "sip the gossip, drink 'til you choke",
    "this half filled battery emoji",
    "skibidi toilet",
    "NixOS > Arch Linux!!",
    "good morning",
    "I'm sorry, Ms. Jackson, I am for real",
    "Poopy-di scoop, Scoop-diddy-whoop, Whoop-di-scoop-di-poop",
    "I want to hold 'em like they do in Texas, please",
    "Hey, I just met you, and this is crazy"
];